# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b9ecfacbf65bf0c4f39bf35a33e5ff0cf0d187e6ad2b97763819dd9f8142dd718d3adbba6832ec3fefe097acab6ecd5edae385c54cf2bf0b613fe3a5da8c99e

test:
  secret_key_base: 2609803ca7b85e86a922c8c46e0e7460597858759c2ff58df17e7f20f21e66be84484fa6c03c29f7837bcd69dfa5e744856ac2391c30dd172b561736e744c6f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
